// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeObI4zjWO347lbaAJEZaXYjbpJasho6o',
    appId: '1:873518395100:web:3da56ab6e18accbb5e0e19',
    messagingSenderId: '873518395100',
    projectId: 'flutter-firebase-tutoria-55da3',
    authDomain: 'flutter-firebase-tutoria-55da3.firebaseapp.com',
    storageBucket: 'flutter-firebase-tutoria-55da3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzvN4xKR8StOrhM1KhUHGZcp6mXgx240w',
    appId: '1:873518395100:android:968076ee8a9bd7cd5e0e19',
    messagingSenderId: '873518395100',
    projectId: 'flutter-firebase-tutoria-55da3',
    storageBucket: 'flutter-firebase-tutoria-55da3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi7PgimOuWxqYBu5d7DwKFrCLOiDBRalY',
    appId: '1:873518395100:ios:8e13895a33961f755e0e19',
    messagingSenderId: '873518395100',
    projectId: 'flutter-firebase-tutoria-55da3',
    storageBucket: 'flutter-firebase-tutoria-55da3.appspot.com',
    iosClientId: '873518395100-q9d6krmbjf9p6dkj3cqi077gc2arh6r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi7PgimOuWxqYBu5d7DwKFrCLOiDBRalY',
    appId: '1:873518395100:ios:8e13895a33961f755e0e19',
    messagingSenderId: '873518395100',
    projectId: 'flutter-firebase-tutoria-55da3',
    storageBucket: 'flutter-firebase-tutoria-55da3.appspot.com',
    iosClientId: '873518395100-q9d6krmbjf9p6dkj3cqi077gc2arh6r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
